# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    storage:    file_system
    mappings:
        stream_video:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
